// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jouiyxqwjlvrabzvhkjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvdWl5eHF3amx2cmFienZoa2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTk0MTUsImV4cCI6MjA3MTc5NTQxNX0.EbngraX7yAJe-mKwpreagioBp75_b8RF0L4nQg3s6Rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});